name: Single Folder CI/CD

on:
    push:
        branches: [main]
        paths:
            - 'test/**'
    pull_request:
        branches: [main]
        paths:
            - 'test/**'
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./test
        steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up environment
            uses: actions/setup-node@v4
            with:
                node-version: '18'
            
          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm test



